version: '3'

services:
  db:
    image: postgres:12
    mem_limit: '128M'
    cpus: 0.1
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pass
    restart: unless-stopped
  backend:
    build: ./backend
    mem_limit: '128M'
    cpus: 0.1
    volumes:
      - ./backend:/app
    ports:
      - 5010:5010
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - FLASK_PORT=5010
      - DB=postgresql://postgres_user:postgres_pass@db:5432/postgres
    restart: unless-stopped
